# See https://pnpm.io/docker
# See also https://www.youtube.com/watch?v=NLjolI9FwCU
FROM node:20-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS prod

COPY ./containers/app/frontend/pnpm-lock.yaml /app
WORKDIR /app
RUN pnpm fetch --prod

COPY . /app
RUN pnpm run build

FROM base
COPY --from=prod /app/node_modules /app/node_modules
COPY --from=prod /app/build-node /app/build-node
EXPOSE 3000
CMD [ "pnpm", "start" ]