services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/user/code/message-board/containers/app/frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /home/user/code/message-board/containers/app/server:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=message_board.app