# See https://www.youtube.com/watch?v=NLjolI9FwCU
name: build + publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push message-board-frontend app
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./containers/app/frontend/Dockerfile.prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/message-board-frontend:latest        
# MORE