name: ci_server

on:
  push:
    branches:
      - main
      - staging
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install FTL CLI
        run: |
          wget https://github.com/yarlson/ftl/releases/latest/download/ftl-linux-amd64
          chmod +x ftl-linux-amd64
          sudo mv ftl-linux-amd64 /usr/local/bin/ftl

      - name: Determine Environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          else
            echo "environment=development" >> $GITHUB_OUTPUT
          fi
  
      - name: Configure Hetzner Credentials
        run: |
          echo "${{ secrets.HETZNER_API_TOKEN }}" | ftl auth login
  
      - name: Deploy with FTL
        run: |
          chmod +x .ftl/deploy.sh
          .ftl/deploy.sh ${{ steps.set-env.outputs.environment }}

      - name: Health Check
        run: |
          sleep 60
          curl https://message-board-server-${{ steps.set-env.outputs.environment }}.yourdomain.com/health
